env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
settings:
  react:
    version: "detect"
rules: { "react/react-in-jsx-scope": "off" }
overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    extends:
      - "eslint:recommended"
      - "plugin:@typescript-eslint/recommended"
    plugins: ["@typescript-eslint"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.json"
